# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='remain_permatently',
            field=models.BooleanField(default=False),
        ),
    ]
